# Generated by Django 5.2.11 on 2026-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('QC', 'QC'), ('REPORTED', 'Reported'), ('ARCHIVED', 'Archived')], default='RECEIVED', max_length=32),
        ),
    ]
