# Generated by Django 5.2.11 on 2026-03-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('samples', '0003_alter_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='projects.project'),
        ),
    ]
