# Generated by Django 5.2.12 on 2026-04-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_sample_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleattachment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_attachments', to='samples.sample'),
        ),
    ]
