# Generated by Django 5.2.12 on 2026-04-16 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_sampleattachment_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleAttachment',
            new_name='SingleSampleAttachment',
        ),
    ]
