# Generated by Django 5.2.15 on 2026-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpost'),
        ('samples', '0010_sample_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='linked_projects',
            field=models.ManyToManyField(blank=True, help_text='Additional projects that can view this sample.', related_name='linked_samples', to='projects.project'),
        ),
    ]
