# Generated by Django 5.2.17 on 2026-08-25 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_lots_and_hierarchy'),
        ('samples', '0013_sample_sample_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='User currently holding the physical sample, when checked out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SampleCustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RECEIVE', 'Receive'), ('CHECK_OUT', 'Check out'), ('CHECK_IN', 'Check in'), ('TRANSFER', 'Transfer custody'), ('MOVE', 'Move storage'), ('PROCESS', 'Record processing'), ('DISPOSE', 'Dispose/archive')], max_length=24)),
                ('scanned_code', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('from_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events_from', to='inventory.container')),
                ('from_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_custody_events', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='samples.sample')),
                ('to_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_events_to', to='inventory.container')),
                ('to_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['sample', '-occurred_at'], name='custody_sample_time_idx'), models.Index(fields=['scanned_code', '-occurred_at'], name='custody_scan_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='SampleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('DERIVED', 'Derived sample'), ('ALIQUOT', 'Aliquot'), ('SPLIT', 'Split'), ('POOL_COMPONENT', 'Pool component')], max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sample_relationships', to=settings.AUTH_USER_MODEL)),
                ('derived_sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='samples.sample')),
                ('source_sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relationships', to='samples.sample')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_sample', models.F('derived_sample')), _negated=True), name='sample_relationship_no_self_link'), models.UniqueConstraint(fields=('source_sample', 'derived_sample', 'relationship_type'), name='sample_relationship_unique_edge')],
            },
        ),
    ]
