# Generated by Django 5.2.15 on 2026-06-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_spec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massspecrun',
            name='chromatogram_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
