# Generated by Django 5.2.15 on 2026-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_spec', '0002_massspecrun_chromatogram_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='massspecrun',
            name='base_peak_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='base_peak_mz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='peak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='top_peaks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
