# Generated by Django 5.2.15 on 2026-06-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_spec', '0003_massspecrun_base_peak_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massspecrun',
            name='detected_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='feature_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='max_total_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='mean_peak_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='mean_total_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='ms1_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='ms2_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='mz_span',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='rt_span',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='total_ion_current',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
