# Generated by Django 5.2.15 on 2026-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_spec', '0004_massspecrun_detected_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massspecrun',
            name='consensusxml_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='featurexml_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='openms_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
