# Generated by Django 5.2.15 on 2026-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_spec', '0005_massspecrun_consensusxml_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massspecrun',
            name='identification_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='peptide_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='protein_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='top_peptides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='massspecrun',
            name='top_proteins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
