import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ, os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

INSTRUMENT_API_KEY = os.getenv("INSTRUMENT_API_KEY", "")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = []
env = environ.Env(DEBUG=(bool, False))
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")
CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", "redis://redis:6379/2")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
            "prefix": "openlims_ws",
        },
    },
}

DEBUG = env.bool("DJANGO_DEBUG", default=True)
SECRET_KEY = env("DJANGO_SECRET_KEY", default="change-me")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'samples',
    'inventory',
    'events',
    'rest_framework',
    'custom_fields',
    'core',
    'results',
    'projects',
    'imports',
    'notifications',
    'sequences',
    'alignments',
    'settings_app',
    'django.contrib.postgres',
    'blast',
    'mass_spec',
    'migration_toolkit',
    'assistant',
    'pipelines',
    'registry',
    'drf_spectacular',
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
SPECTACULAR_SETTINGS = {
    "TITLE": "OpenLIMS API",
    "DESCRIPTION": "Versioned OpenLIMS laboratory information management API.",
    "VERSION": "1.0.0",
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    "SERVE_INCLUDE_SCHEMA": False,
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=2),
    "ROTATE_REFRESH_TOKENS": False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    "default": env.db("DATABASE_URL", default="sqlite:///db.sqlite3")
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'
#MEDIA_URL='/media/'
#MEDIA_ROOT = BASE_DIR/'media'
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Read-only legacy database migration sources. Remote hosts must be explicitly
# allowed; SQLite files must stay below the configured source directory.
MIGRATION_DB_ALLOWED_HOSTS = env.list(
    "MIGRATION_DB_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "db", "host.docker.internal"],
)
MIGRATION_DB_CONNECT_TIMEOUT = env.int("MIGRATION_DB_CONNECT_TIMEOUT", default=10)
MIGRATION_DB_MAX_ROWS = env.int("MIGRATION_DB_MAX_ROWS", default=50000)
MIGRATION_SQLITE_ROOT = Path(
    os.getenv("MIGRATION_SQLITE_ROOT", str(BASE_DIR / "migration_sources"))
)
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Optional LLM support for the OpenLIMS Assistant. Models can classify or explain,
# but validated OpenLIMS routes remain authoritative for reads and confirmed writes.
OPENLIMS_ASSISTANT_LLM_PROVIDER = os.getenv("OPENLIMS_ASSISTANT_LLM_PROVIDER", "openai")
OPENLIMS_ASSISTANT_LLM_ENABLED = os.getenv(
    "OPENLIMS_ASSISTANT_LLM_ENABLED",
    "false",
).lower() in ["1", "true", "yes", "on"]
OPENLIMS_ASSISTANT_LLM_ROUTING_ENABLED = os.getenv(
    "OPENLIMS_ASSISTANT_LLM_ROUTING_ENABLED",
    "true",
).lower() in ["1", "true", "yes", "on"]
OPENLIMS_ASSISTANT_LLM_ROUTING_MIN_CONFIDENCE = float(
    os.getenv("OPENLIMS_ASSISTANT_LLM_ROUTING_MIN_CONFIDENCE", "0.65")
)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-mini")

# Optional local Ollama support for the OpenLIMS Assistant.
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://host.docker.internal:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1")
OLLAMA_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "60"))
