# Generated by Django 5.2.17 on 2026-08-25 04:59

from django.db import migrations, models


def preserve_sequential_dependencies(apps, schema_editor):
    TemplateStep = apps.get_model("pipelines", "PipelineTemplateStep")
    StepRun = apps.get_model("pipelines", "PipelineStepRun")
    for model, owner_field in [
        (TemplateStep, "template_id"),
        (StepRun, "pipeline_run_id"),
    ]:
        current_owner = None
        previous_position = None
        for step in model.objects.order_by(owner_field, "position"):
            owner = getattr(step, owner_field)
            if owner != current_owner:
                current_owner = owner
                previous_position = None
            step.dependency_positions = [] if previous_position is None else [previous_position]
            step.save(update_fields=["dependency_positions"])
            previous_position = step.position


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesteprun',
            name='activation_condition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinesteprun',
            name='dependency_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pipelinesteprun',
            name='max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinesteprun',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinesteprun',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinetemplatestep',
            name='activation_condition',
            field=models.JSONField(blank=True, default=dict, help_text='Optional result-based condition evaluated after dependencies complete.'),
        ),
        migrations.AddField(
            model_name='pipelinetemplatestep',
            name='dependency_positions',
            field=models.JSONField(blank=True, default=None, help_text='Positions that must complete before this step can start.', null=True),
        ),
        migrations.AddField(
            model_name='pipelinetemplatestep',
            name='max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinetemplatestep',
            name='optional',
            field=models.BooleanField(default=False, help_text='Allow the workflow to continue when this step fails or is cancelled.'),
        ),
        migrations.AlterField(
            model_name='pipelinesteprun',
            name='status',
            field=models.CharField(choices=[('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QC', 'Awaiting QC'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='BLOCKED', max_length=16),
        ),
        migrations.RunPython(preserve_sequential_dependencies, migrations.RunPython.noop),
    ]
