# Generated by Django 5.2.17 on 2026-09-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_step_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesteprun',
            name='automation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinetemplatestep',
            name='automation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
