# Generated by Django 5.2.15 on 2026-06-30 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectpost'),
        ('samples', '0011_sample_linked_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('source_system', models.CharField(default='Legacy DB', max_length=128)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV')], default='CSV', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='migration_jobs/')),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=32)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='migration_toolkit.migrationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=128)),
                ('target_type', models.CharField(choices=[('PROJECT_CODE', 'Project Code'), ('PROJECT_NAME', 'Project Name'), ('SAMPLE_ID', 'Sample ID'), ('EXTERNAL_ID', 'External ID / Alias'), ('CUSTOM_FIELD', 'Sample Custom Field'), ('WORK_ITEM_NAME', 'Work Item Name'), ('RESULT_VALUE', 'Result Value')], max_length=64)),
                ('target_field', models.CharField(blank=True, help_text='Used for custom field name, external ID label, or result key.', max_length=128)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='migration_toolkit.migrationprofile')),
            ],
            options={
                'unique_together': {('profile', 'source_column', 'target_type', 'target_field')},
            },
        ),
        migrations.CreateModel(
            name='SampleExternalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=128)),
                ('external_id', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='samples.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['source_system', 'external_id'], name='migration_t_source__6aff85_idx'), models.Index(fields=['label'], name='migration_t_label_cdeca8_idx')],
                'unique_together': {('source_system', 'external_id', 'label')},
            },
        ),
    ]
