# Generated by Django 5.2.15 on 2026-07-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_toolkit', '0001_initial'),
        ('projects', '0003_projectpost'),
        ('samples', '0011_sample_linked_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('project_code', models.CharField(blank=True, max_length=128)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('sample_code', models.CharField(blank=True, max_length=128)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('unmapped_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], default='IMPORTED', max_length=32)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migration_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_records', to='migration_toolkit.migrationjob')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_row_records', to='projects.project')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_row_records', to='samples.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['migration_job', 'row_number'], name='migration_t_migrati_72fe5b_idx'), models.Index(fields=['project', 'sample'], name='migration_t_project_be7bb0_idx'), models.Index(fields=['sample_code'], name='migration_t_sample__e1c376_idx'), models.Index(fields=['project_code'], name='migration_t_project_0edf19_idx'), models.Index(fields=['status'], name='migration_t_status_efcab3_idx')],
                'unique_together': {('migration_job', 'row_number')},
            },
        ),
    ]
