# Generated by Django 5.2.15 on 2026-07-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_toolkit', '0002_migrationrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrowrecord',
            name='raw_row_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PREVIEWED', 'Previewed'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILED', 'Partial Failed'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=32),
        ),
    ]
