# Generated by Django 5.2.17 on 2026-08-25 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_toolkit', '0004_database_migration_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='conflict_policy',
            field=models.CharField(choices=[('SKIP', 'Skip existing records'), ('MERGE', 'Fill blank fields on existing records'), ('OVERWRITE', 'Overwrite mapped fields'), ('CREATE_NEW', 'Create a new record with a unique identifier')], default='SKIP', max_length=32),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='rollback_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_migration_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='migrationrowrecord',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('MATCH', 'Matched'), ('SKIP', 'Skipped'), ('MERGE', 'Merged'), ('OVERWRITE', 'Overwritten'), ('CREATE_NEW', 'Created with a new identifier'), ('ERROR', 'Error')], default='CREATE', max_length=32),
        ),
        migrations.AddField(
            model_name='migrationrowrecord',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='migrationrowrecord',
            name='target_object_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PREVIEWED', 'Previewed'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILED', 'Partial Failed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PREVIEWED', max_length=32),
        ),
        migrations.CreateModel(
            name='MigrationMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('source_system', models.CharField(default='Legacy DB', max_length=128)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV'), ('DATABASE', 'Database')], default='CSV', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_mapping_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MigrationObjectChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated')], max_length=16)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=64)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migration_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_changes', to='migration_toolkit.migrationjob')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['migration_job', 'action'], name='migration_t_migrati_75c7d2_idx'), models.Index(fields=['object_type', 'object_id'], name='migration_t_object__5c7f76_idx')],
                'constraints': [models.UniqueConstraint(fields=('migration_job', 'object_type', 'object_id', 'action'), name='migration_object_change_unique')],
            },
        ),
    ]
