# Generated by Django 5.2.17 on 2026-08-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_toolkit', '0005_migrationjob_conflict_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationdataset',
            name='entity_type',
            field=models.CharField(choices=[('PROJECT', 'Projects'), ('USER', 'Users'), ('SAMPLE', 'Samples'), ('RESULT', 'Historical results'), ('REGISTRY', 'Registry records')], max_length=32),
        ),
        migrations.AlterField(
            model_name='migrationfieldmapping',
            name='target_type',
            field=models.CharField(choices=[('PROJECT_CODE', 'Project Code'), ('PROJECT_NAME', 'Project Name'), ('SAMPLE_ID', 'Sample ID'), ('EXTERNAL_ID', 'External ID / Alias'), ('CUSTOM_FIELD', 'Sample Custom Field'), ('WORK_ITEM_NAME', 'Work Item Name'), ('RESULT_VALUE', 'Result Value'), ('PROJECT_DESCRIPTION', 'Project Description'), ('USER_USERNAME', 'User Username'), ('USER_EMAIL', 'User Email'), ('USER_FIRST_NAME', 'User First Name'), ('USER_LAST_NAME', 'User Last Name'), ('USER_ROLE', 'User Role'), ('SAMPLE_TYPE', 'Sample Type'), ('SAMPLE_STATUS', 'Sample Status'), ('SAMPLE_CREATED_AT', 'Sample Created At'), ('WORK_ITEM_TYPE', 'Work Item Type'), ('WORK_ITEM_STATUS', 'Work Item Status'), ('WORK_ITEM_CREATED_AT', 'Work Item Created At'), ('RESULT_KEY', 'Result Key'), ('RESULT_UNIT', 'Result Unit'), ('RESULT_CREATED_AT', 'Result Created At'), ('RESULT_QC_STATUS', 'Result QC Status'), ('RESULT_ENTERED_BY', 'Result Entered By'), ('RESULT_REFERENCE_MIN', 'Result Reference Minimum'), ('RESULT_REFERENCE_MAX', 'Result Reference Maximum'), ('REGISTRY_ID', 'Registry ID'), ('REGISTRY_SCHEMA', 'Registry Schema Code'), ('REGISTRY_NAME', 'Registry Record Name'), ('REGISTRY_DESCRIPTION', 'Registry Description'), ('REGISTRY_CATALOG_NUMBER', 'Registry Catalog Number'), ('REGISTRY_ALIAS', 'Registry Alias'), ('REGISTRY_TAGS', 'Registry Tags'), ('REGISTRY_STATUS', 'Registry Lifecycle Status'), ('REGISTRY_DATA', 'Registry Data Field'), ('REGISTRY_SEQUENCE', 'Registry Sequence')], max_length=64),
        ),
    ]
