# Generated by Django 5.2.14 on 2026-05-31 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default='OpenLIMS Demo Lab', max_length=255)),
                ('organization_name', models.CharField(default='OpenLIMS', max_length=255)),
                ('default_timezone', models.CharField(default='UTC', max_length=100)),
                ('default_sample_status', models.CharField(default='RECEIVED', max_length=50)),
                ('max_upload_size_mb', models.PositiveIntegerField(default=10)),
                ('require_import_preview', models.BooleanField(default=True)),
                ('allowed_fasta_extensions', models.JSONField(blank=True, default=list)),
                ('alignments_enabled', models.BooleanField(default=True)),
                ('max_sequences_per_alignment', models.PositiveIntegerField(default=25)),
                ('max_sequence_length', models.PositiveIntegerField(default=100000)),
                ('viewer_read_only', models.BooleanField(default=True)),
                ('require_audit_reason', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
