# Generated by Django 5.2.17 on 2026-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_printtemplate_workspaceview'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='assistant_helper_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
