# Generated by Django 5.2.14 on 2026-05-27 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectpost'),
        ('sequences', '0002_sequence_import_job_sequence_source_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tool', models.CharField(choices=[('CLUSTAL_OMEGA', 'Clustal Omega')], default='CLUSTAL_OMEGA', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('input_fasta', models.TextField(blank=True)),
                ('aligned_fasta', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_jobs', to='projects.project')),
                ('sequences', models.ManyToManyField(blank=True, related_name='alignment_jobs', to='sequences.sequence')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
