# Generated by Django 5.2.14 on 2026-05-19 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectpost'),
        ('samples', '0009_rename_sampleattachment_singlesampleattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('PROTEIN', 'Protein')], default='DNA', max_length=20)),
                ('sequence', models.TextField()),
                ('viewer', models.CharField(default='both', max_length=50)),
                ('show_complement', models.BooleanField(default=True)),
                ('rotate_on_scroll', models.BooleanField(default=False)),
                ('zoom', models.IntegerField(default=50)),
                ('enzymes', models.JSONField(blank=True, default=list)),
                ('bp_colors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequences', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='projects.project')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='samples.sample')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('ANNOTATION', 'Annotation'), ('PRIMER', 'Primer'), ('TRANSLATION', 'Translation'), ('HIGHLIGHT', 'Highlight')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('direction', models.IntegerField(default=1)),
                ('color', models.CharField(default='#22c55e', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sequences.sequence')),
            ],
            options={
                'ordering': ['start', 'end', 'id'],
            },
        ),
    ]
