# Generated by Django 5.2.14 on 2026-05-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_alter_importjob_source_type_alter_importjob_status'),
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='imports.importjob'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sequence',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FASTA_IMPORT', 'FASTA Import'), ('FASTQ_IMPORT', 'FASTQ Import'), ('GENBANK_IMPORT', 'GenBank Import')], default='MANUAL', max_length=30),
        ),
    ]
