# Generated by Django 5.2.17 on 2026-08-26 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_public_id'),
        ('registry', '0001_initial'),
        ('sequences', '0003_sequence_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='topology',
            field=models.CharField(choices=[('LINEAR', 'Linear'), ('CIRCULAR', 'Circular')], default='LINEAR', max_length=16),
        ),
        migrations.AddField(
            model_name='sequencefeature',
            name='gc_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencefeature',
            name='melting_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencefeature',
            name='primer_sequence',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ConstructAssemblyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(default='SIMPLE_FRAGMENT_ASSEMBLY', max_length=64)),
                ('cloning_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSEMBLED', 'Assembled')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assembly_plans', to=settings.AUTH_USER_MODEL)),
                ('target_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_plans', to='sequences.sequence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceFeatureLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('ANNOTATION', 'Annotation'), ('PRIMER', 'Primer'), ('TRANSLATION', 'Translation'), ('HIGHLIGHT', 'Highlight')], max_length=30)),
                ('sequence_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('PROTEIN', 'Protein')], default='DNA', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('color', models.CharField(default='#22c55e', max_length=30)),
                ('qualifiers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequence_features', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_feature_library', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sequencefeature',
            name='library_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_features', to='sequences.sequencefeaturelibrary'),
        ),
        migrations.CreateModel(
            name='SequenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('sequence_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('PROTEIN', 'Protein')], max_length=20)),
                ('topology', models.CharField(choices=[('LINEAR', 'Linear'), ('CIRCULAR', 'Circular')], max_length=16)),
                ('sequence', models.TextField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequence_revisions', to=settings.AUTH_USER_MODEL)),
                ('registry_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_revisions', to='registry.registryrecord')),
                ('sequence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sequences.sequence')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('start', models.PositiveIntegerField(default=0)),
                ('end', models.PositiveIntegerField(blank=True, null=True)),
                ('reverse_complement', models.BooleanField(default=False)),
                ('left_overhang', models.CharField(blank=True, max_length=64)),
                ('right_overhang', models.CharField(blank=True, max_length=64)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='sequences.constructassemblyplan')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_fragments', to='sequences.sequencerevision')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_sequences', to='sequences.sequencerevision'),
        ),
        migrations.CreateModel(
            name='SequenceRevisionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feature_type', models.CharField(choices=[('ANNOTATION', 'Annotation'), ('PRIMER', 'Primer'), ('TRANSLATION', 'Translation'), ('HIGHLIGHT', 'Highlight')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('direction', models.IntegerField(default=1)),
                ('color', models.CharField(default='#22c55e', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('primer_sequence', models.TextField(blank=True)),
                ('melting_temperature', models.FloatField(blank=True, null=True)),
                ('gc_content', models.FloatField(blank=True, null=True)),
                ('library_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_features', to='sequences.sequencefeaturelibrary')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sequences.sequencerevision')),
            ],
            options={
                'ordering': ['start', 'end', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sequencefeaturelibrary',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'sequence_type'), name='sequence_feature_library_unique'),
        ),
        migrations.AddConstraint(
            model_name='sequencerevision',
            constraint=models.UniqueConstraint(fields=('sequence_record', 'revision'), name='sequence_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='assemblyfragment',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='assembly_fragment_order_unique'),
        ),
    ]
