# Generated by Django 5.2.10 on 2026-01-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(max_length=64)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='inventory.location')),
            ],
        ),
    ]
