# Generated by Django 5.2.17 on 2026-08-27 00:30

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_public_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('barcode', models.CharField(max_length=128, unique=True)),
                ('object_id', models.CharField(max_length=64)),
                ('target_public_id', models.UUIDField(db_index=True)),
                ('entity_type', models.SlugField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('EXPIRATION', 'Expiration'), ('LOW_STOCK', 'Low stock'), ('REORDER', 'Reorder'), ('RESERVATION', 'Reservation')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('deduplication_key', models.CharField(max_length=255, unique=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('RECONCILED', 'Reconciled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('observed_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lot__lot_code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['container', 'position'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(choices=[('RECEIVE', 'Receive'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('COUNT', 'Count'), ('CONSUME', 'Consume'), ('ADJUST', 'Adjust'), ('QUARANTINE', 'Quarantine'), ('DISPOSE', 'Dispose'), ('RETURN', 'Return')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unit', models.CharField(max_length=32)),
                ('before_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('after_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('before_status', models.CharField(max_length=32)),
                ('after_status', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('request_item_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='columns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='catalog_number',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='chemical_identity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='coa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='concentration',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='disposal_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ghs_classifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hazard_statements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sds_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='quarantine_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
