# Generated by Django 5.2.15 on 2026-06-08 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectpost'),
        ('sequences', '0002_sequence_import_job_sequence_source_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('database_type', models.CharField(choices=[('DNA', 'DNA'), ('PROTEIN', 'Protein')], default='DNA', max_length=20)),
                ('source_fasta', models.FileField(blank=True, null=True, upload_to='blast_databases/source_fastas/')),
                ('db_path', models.CharField(blank=True, help_text='Path prefix to the built BLAST database inside the container.', max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('BUILDING', 'Building'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NEW', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('blastn', 'blastn'), ('blastp', 'blastp')], default='blastn', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('max_target_seqs', models.PositiveIntegerField(default=25)),
                ('evalue', models.CharField(default='10', max_length=50)),
                ('query_fasta', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('hits_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_jobs', to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_jobs', to='blast.blastdatabase')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_jobs', to='projects.project')),
                ('query_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_jobs', to='sequences.sequence')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BlastHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('hit_id', models.CharField(blank=True, max_length=500)),
                ('hit_def', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=255)),
                ('hit_length', models.PositiveIntegerField(default=0)),
                ('bit_score', models.FloatField(blank=True, null=True)),
                ('evalue', models.FloatField(blank=True, null=True)),
                ('identity_percent', models.FloatField(blank=True, null=True)),
                ('alignment_length', models.PositiveIntegerField(default=0)),
                ('query_from', models.PositiveIntegerField(blank=True, null=True)),
                ('query_to', models.PositiveIntegerField(blank=True, null=True)),
                ('hit_from', models.PositiveIntegerField(blank=True, null=True)),
                ('hit_to', models.PositiveIntegerField(blank=True, null=True)),
                ('query_aligned', models.TextField(blank=True)),
                ('hit_aligned', models.TextField(blank=True)),
                ('midline', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='blast.blastjob')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
    ]
