# Generated by Django 5.2.12 on 2026-04-18 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('has_header', models.BooleanField(default=True)),
                ('sample_id_column', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='imports.instrumentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=128)),
                ('target_key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('STRING', 'STRING'), ('NUMBER', 'NUMBER'), ('BOOLEAN', 'BOOLEAN')], max_length=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='imports.instrumentprofile')),
            ],
            options={
                'unique_together': {('instrument', 'source_column')},
            },
        ),
    ]
