# Generated by Django 5.2.12 on 2026-04-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('projects', '0003_projectpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='projects.project'),
        ),
    ]
