# Generated by Django 5.2.12 on 2026-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcolumnmapping',
            name='allowed_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentcolumnmapping',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentcolumnmapping',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
