# Generated by Django 5.2.12 on 2026-04-22 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_instrumentcolumnmapping_allowed_values_and_more'),
        ('projects', '0003_projectpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='run_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('API', 'API')], default='UPLOAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('run_id__isnull', False)), fields=('instrument', 'run_id'), name='unique_instrument_run_id'),
        ),
    ]
