# Generated by Django 5.2.13 on 2026-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importjob_run_id_importjob_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importjob',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
