# Generated by Django 5.2.14 on 2026-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_importjob_progress_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('API', 'API'), ('SEQUENCE_FASTA', 'SEQUENCE_FASTA')], default='UPLOAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
