# Generated by Django 5.2.15 on 2026-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_alter_importjob_source_type_alter_importjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentprofile',
            name='auto_detect_header',
            field=models.BooleanField(default=True, help_text='Auto-detect the header row using the sample ID column.'),
        ),
        migrations.AddField(
            model_name='instrumentprofile',
            name='header_row_index',
            field=models.PositiveIntegerField(default=0, help_text='Zero-based row index where the CSV header starts.'),
        ),
    ]
