# Generated by Django 5.2.17 on 2026-08-09 21:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_qc_inventory_action_types'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0003_projectpost'),
        ('samples', '0012_sample_batches_and_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantaction',
            name='action_type',
            field=models.CharField(choices=[('RUN_BLAST', 'Run BLAST'), ('RUN_ALIGNMENT', 'Run alignment'), ('CREATE_MIGRATION_MAPPINGS', 'Create migration mappings'), ('QUEUE_REPORT', 'Queue report'), ('QUEUE_IMPORT', 'Queue import'), ('CREATE_SAMPLES', 'Create samples'), ('BULK_SAMPLE_UPDATE', 'Bulk sample update'), ('QC_REVIEW', 'QC review'), ('INVENTORY_OPERATION', 'Inventory operation'), ('WORK_ITEM_OPERATION', 'Work-item operation'), ('LABEL_GENERATION', 'Label generation'), ('COMPLIANCE_REPORT', 'Compliance report'), ('NOTIFICATION_MANAGEMENT', 'Notification management')], max_length=40),
        ),
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('LABEL_PDF', 'Label PDF'), ('REPORT_PDF', 'Report PDF'), ('REPORT_CSV', 'Report CSV')], max_length=24)),
                ('file', models.FileField(upload_to='assistant_artifacts/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_assistant_artifacts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_artifacts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=64)),
                ('delivery_channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], default='IN_APP', max_length=16)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily summary')], default='ONCE', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=128)),
                ('threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deduplication_key', models.CharField(max_length=255, unique=True)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=16)),
                ('permission_rechecked', models.BooleanField(default=False)),
                ('detail', models.JSONField(default=dict)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='assistant.notificationsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('section', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('source_file', models.FileField(blank=True, null=True, upload_to='sops/')),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], default='CURRENT', max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='sop_documents', to='auth.group')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sop_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_code', 'section', '-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='STANDARD_SAMPLE', max_length=64)),
                ('barcode', models.CharField(max_length=128, unique=True)),
                ('generation_count', models.PositiveIntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_barcode_labels', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_labels', to='samples.sample')),
                ('last_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_labels', to='assistant.generatedartifact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sample', 'template'), name='barcode_sample_template_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationsubscription',
            index=models.Index(fields=['active', 'next_run_at'], name='notify_active_next_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'event_key'), name='notification_delivery_unique'),
        ),
        migrations.AddConstraint(
            model_name='sopdocument',
            constraint=models.UniqueConstraint(fields=('document_code', 'version', 'section'), name='sop_code_version_section_unique'),
        ),
    ]
