# Generated by Django 5.2.17 on 2026-08-09 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_assistantaction_action_type_generatedartifact_and_more'),
        ('projects', '0003_projectpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscription',
            name='deduplication_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='notificationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('deduplication_key',), name='active_notification_dedup_unique'),
        ),
    ]
