# Generated by Django 5.2.17 on 2026-08-27 00:30

import django.db.models.deletion
import django.db.models.functions.text
import uuid
import workflow_requests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_inventoryreservation_experiment_and_more'),
        ('pipelines', '0003_pipelinerun_public_id'),
        ('projects', '0004_project_public_id'),
        ('registry', '0002_initial'),
        ('samples', '0015_sample_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('form_schema', models.JSONField(blank=True, default=dict)),
                ('default_priority', models.CharField(default='NORMAL', max_length=16)),
                ('sla_hours', models.PositiveIntegerField(default=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assay_request_types', to=settings.AUTH_USER_MODEL)),
                ('default_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assay_request_types', to='pipelines.pipelinetemplate')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_request_types', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RequestResourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('MATERIAL', 'Material'), ('INSTRUMENT', 'Instrument'), ('PERSONNEL', 'Personnel role'), ('DURATION', 'Estimated duration')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('instrument_name', models.CharField(blank=True, max_length=255)),
                ('personnel_role', models.CharField(blank=True, max_length=128)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('pipeline_step_position', models.PositiveIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_resource_requirements', to='inventory.inventoryitem')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='workflow_requests.assayrequesttype')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('TRIAGE', 'Triage'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflow_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests', to='pipelines.pipelinetemplate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests', to='projects.project')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflow_requests.assayrequesttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests', to=settings.AUTH_USER_MODEL)),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_workflow_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('study_public_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_request_items', to='pipelines.pipelinerun')),
                ('registry_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_request_items', to='registry.registryrecord')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workflow_requests.workflowrequest')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_request_items', to='samples.sample')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('internal_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_request_messages', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflow_requests.workflowrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=workflow_requests.models.request_report_upload_to)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflow_request_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='workflow_requests.workflowrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_workflow_request_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_run_groups', to='samples.samplebatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_run_groups', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='run_groups', to='workflow_requests.workflowrequestitem')),
                ('pipeline_runs', models.ManyToManyField(blank=True, related_name='workflow_request_groups', to='pipelines.pipelinerun')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_run_groups', to='inventory.container')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_groups', to='workflow_requests.workflowrequest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='assayrequesttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='workflow_request_type_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['project', 'status', 'priority'], name='workflow_re_project_8760c8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['requester', 'status'], name='workflow_re_request_867697_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrequestitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sample__isnull', False)), fields=('request', 'sample'), name='workflow_request_sample_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflowrequestitem',
            constraint=models.UniqueConstraint(condition=models.Q(('registry_record__isnull', False)), fields=('request', 'registry_record'), name='workflow_request_registry_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflowrungroup',
            constraint=models.UniqueConstraint(fields=('request', 'name'), name='workflow_request_run_group_name_unique'),
        ),
    ]
