export const ASSISTANT_STARTER_PROMPTS = [
  "What needs attention?",
  "Investigate why sample S-ALPHA-003 failed QC",
  "Compare samples S-ALPHA-001, S-ALPHA-002, and S-ALPHA-003",
  "Compare projects Alpha, Beta, and Gamma",
  "Find unusual results in Project Alpha",
  "Where are samples getting stuck?",
  "Find sample S-ALPHA-003",
  "Summarize sample S-ALPHA-003",
  "Which samples in Project Alpha are awaiting processing?",
  "Show results that failed QC this week",
  "Which reagents expire in the next 30 days?",
  "Show inventory below its reorder level",
  "Where is sample S-ALPHA-001?",
  "Find sequences for sample S-ALPHA-001",
  "Summarize sequence records for sample S-ALPHA-001",
  "Prepare BLAST for sample S-ALPHA-001",
  "Chart samples by status",
  "How do I receive a sample?",
  "Show system status",
];
