# Generated by Django 5.2.10 on 2026-01-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('data_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('bool', 'bool'), ('date', 'date'), ('json', 'json')], default='string', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('entity_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.fielddefinition')),
            ],
            options={
                'unique_together': {('field_definition', 'entity_type', 'entity_id')},
            },
        ),
    ]
