# Generated by Django 5.2.17 on 2026-08-26 05:33

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('sequences', '0004_sequence_topology_sequencefeature_gc_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registryrecordversion',
            name='sequence_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registry_versions', to='sequences.sequencerevision'),
        ),
        migrations.AddField(
            model_name='registryrecord',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_records', to='registry.registryrecordversion'),
        ),
        migrations.AddField(
            model_name='registrationreview',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='registry.registryrecordversion'),
        ),
        migrations.AddField(
            model_name='registryrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registry_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registryrelationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='registry.registryrecord'),
        ),
        migrations.AddField(
            model_name='registryrelationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='registry.registryrecord'),
        ),
        migrations.AddField(
            model_name='registryschema',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registry_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registryrecordversion',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_versions', to='registry.registryschema'),
        ),
        migrations.AddField(
            model_name='registryrecord',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='registry.registryschema'),
        ),
        migrations.AddIndex(
            model_name='registryalias',
            index=models.Index(fields=['alias'], name='registry_re_alias_6bcda6_idx'),
        ),
        migrations.AddConstraint(
            model_name='registryalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('alias'), models.F('record'), name='registry_record_alias_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='registrationreview',
            constraint=models.UniqueConstraint(condition=models.Q(('decision', 'PENDING')), fields=('record',), name='registry_one_pending_review'),
        ),
        migrations.AddConstraint(
            model_name='registryrelationship',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relationship_type', 'custom_type'), name='registry_relationship_unique'),
        ),
        migrations.AddIndex(
            model_name='registryschema',
            index=models.Index(fields=['entity_type', 'active'], name='registry_re_entity__d74901_idx'),
        ),
        migrations.AddConstraint(
            model_name='registryschema',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='registry_schema_code_version_unique'),
        ),
        migrations.AddIndex(
            model_name='registryrecordversion',
            index=models.Index(fields=['sequence_checksum'], name='registry_re_sequenc_b0006c_idx'),
        ),
        migrations.AddConstraint(
            model_name='registryrecordversion',
            constraint=models.UniqueConstraint(fields=('record', 'version'), name='registry_record_version_unique'),
        ),
        migrations.AddIndex(
            model_name='registryrecord',
            index=models.Index(fields=['project', 'lifecycle_status'], name='registry_re_project_f2531f_idx'),
        ),
        migrations.AddIndex(
            model_name='registryrecord',
            index=models.Index(fields=['schema', 'lifecycle_status'], name='registry_re_schema__bd998e_idx'),
        ),
        migrations.AddIndex(
            model_name='registryrecord',
            index=models.Index(fields=['catalog_number'], name='registry_re_catalog_cff616_idx'),
        ),
    ]
