# Generated by Django 5.2.17 on 2026-08-27 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_experiments', to=settings.AUTH_USER_MODEL)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='notebook.experiment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experiments', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiment_revisions', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='notebook.experiment')),
                ('parent_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_revisions', to='notebook.experimentrevision')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restore_revisions', to='notebook.experimentrevision')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested')], max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('signed_name', models.CharField(max_length=255)),
                ('content_checksum', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='notebook.experiment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_reviews', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='notebook.experimentrevision')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.SlugField(max_length=64)),
                ('entity_public_id', models.UUIDField()),
                ('relation_type', models.SlugField(default='used', max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('version', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiment_links', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='notebook.experimentrevision')),
            ],
            options={
                'ordering': ['entity_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_experiment_comments', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_comments', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='notebook.experiment')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_experiment_comments', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_experiment_comments', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='notebook.experimentrevision')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('RICH_TEXT', 'Rich text'), ('HEADING', 'Heading'), ('TABLE', 'Table'), ('CHECKLIST', 'Checklist'), ('PROTOCOL_STEP', 'Protocol step'), ('CALCULATION', 'Calculation'), ('IMAGE', 'Image'), ('ATTACHMENT', 'Attachment'), ('STRUCTURED_RESULT', 'Structured result'), ('SEQUENCE_VIEW', 'Embedded sequence view')], max_length=24)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='notebook.experimentrevision')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_experiments', to='notebook.experimentrevision'),
        ),
        migrations.CreateModel(
            name='ExperimentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='notebook.experimenttemplate'),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('USER', 'User'), ('TEAM', 'Team'), ('PROJECT', 'Project')], default='USER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commenters', models.ManyToManyField(blank=True, related_name='commentable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='editable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('lockers', models.ManyToManyField(blank=True, related_name='lockable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_notebooks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notebooks', to='projects.project')),
                ('readers', models.ManyToManyField(blank=True, related_name='readable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='reviewable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='experimenttemplate',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='notebook.notebook'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='notebook.notebook'),
        ),
        migrations.AddConstraint(
            model_name='experimentrevision',
            constraint=models.UniqueConstraint(fields=('experiment', 'number'), name='notebook_experiment_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='experimentreview',
            constraint=models.UniqueConstraint(fields=('revision', 'reviewer'), name='notebook_revision_reviewer_unique'),
        ),
        migrations.AddConstraint(
            model_name='experimentlink',
            constraint=models.UniqueConstraint(fields=('revision', 'entity_type', 'entity_public_id', 'relation_type'), name='notebook_revision_entity_link_unique'),
        ),
        migrations.AddConstraint(
            model_name='experimentblock',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='notebook_revision_block_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='experimenttemplate',
            constraint=models.UniqueConstraint(fields=('notebook', 'name'), name='notebook_template_name_unique'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['status', 'updated_at'], name='notebook_ex_status_d326c7_idx'),
        ),
    ]
